/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PaymentStreamV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_STREAM_DURATION"
      | "MIN_STREAM_DURATION"
      | "autoRenewalEnabled"
      | "availableBalance"
      | "cancelStream"
      | "createStream"
      | "feeRecipient"
      | "getAllStreamsForAddress"
      | "getRecipientStreams"
      | "getSenderStreams"
      | "getStream"
      | "getStreamsByStatus"
      | "owner"
      | "pauseStream"
      | "platformFeeBps"
      | "recipientStreams"
      | "renounceOwnership"
      | "resumeStream"
      | "senderStreams"
      | "setAutoRenewal"
      | "setFeeRecipient"
      | "setPlatformFee"
      | "streamCount"
      | "streams"
      | "transferOwnership"
      | "usdt"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutoRenewalToggled"
      | "NotificationSent"
      | "OwnershipTransferred"
      | "StreamCancelled"
      | "StreamCompleted"
      | "StreamCreated"
      | "StreamPaused"
      | "StreamRenewed"
      | "StreamResumed"
      | "StreamWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_STREAM_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_STREAM_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "autoRenewalEnabled",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "availableBalance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelStream",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createStream",
    values: [AddressLike, BigNumberish, BigNumberish, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllStreamsForAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecipientStreams",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSenderStreams",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStream",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStreamsByStatus",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseStream",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recipientStreams",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resumeStream",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "senderStreams",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAutoRenewal",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "streamCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "streams", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "MAX_STREAM_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_STREAM_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoRenewalEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllStreamsForAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecipientStreams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSenderStreams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStream", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStreamsByStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recipientStreams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resumeStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "senderStreams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAutoRenewal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "streams", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AutoRenewalToggledEvent {
  export type InputTuple = [
    sender: AddressLike,
    recipient: AddressLike,
    enabled: boolean
  ];
  export type OutputTuple = [
    sender: string,
    recipient: string,
    enabled: boolean
  ];
  export interface OutputObject {
    sender: string;
    recipient: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NotificationSentEvent {
  export type InputTuple = [
    streamId: BytesLike,
    recipient: AddressLike,
    notificationType: string,
    message: string
  ];
  export type OutputTuple = [
    streamId: string,
    recipient: string,
    notificationType: string,
    message: string
  ];
  export interface OutputObject {
    streamId: string;
    recipient: string;
    notificationType: string;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamCancelledEvent {
  export type InputTuple = [
    streamId: BytesLike,
    sender: AddressLike,
    remainingAmount: BigNumberish
  ];
  export type OutputTuple = [
    streamId: string,
    sender: string,
    remainingAmount: bigint
  ];
  export interface OutputObject {
    streamId: string;
    sender: string;
    remainingAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamCompletedEvent {
  export type InputTuple = [streamId: BytesLike, autoRenewed: boolean];
  export type OutputTuple = [streamId: string, autoRenewed: boolean];
  export interface OutputObject {
    streamId: string;
    autoRenewed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamCreatedEvent {
  export type InputTuple = [
    streamId: BytesLike,
    sender: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish,
    serviceId: string,
    autoRenew: boolean
  ];
  export type OutputTuple = [
    streamId: string,
    sender: string,
    recipient: string,
    amount: bigint,
    startTime: bigint,
    endTime: bigint,
    serviceId: string,
    autoRenew: boolean
  ];
  export interface OutputObject {
    streamId: string;
    sender: string;
    recipient: string;
    amount: bigint;
    startTime: bigint;
    endTime: bigint;
    serviceId: string;
    autoRenew: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamPausedEvent {
  export type InputTuple = [
    streamId: BytesLike,
    pausedAt: BigNumberish,
    remainingTime: BigNumberish
  ];
  export type OutputTuple = [
    streamId: string,
    pausedAt: bigint,
    remainingTime: bigint
  ];
  export interface OutputObject {
    streamId: string;
    pausedAt: bigint;
    remainingTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamRenewedEvent {
  export type InputTuple = [
    streamId: BytesLike,
    newStreamId: BytesLike,
    amount: BigNumberish,
    newEndTime: BigNumberish
  ];
  export type OutputTuple = [
    streamId: string,
    newStreamId: string,
    amount: bigint,
    newEndTime: bigint
  ];
  export interface OutputObject {
    streamId: string;
    newStreamId: string;
    amount: bigint;
    newEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamResumedEvent {
  export type InputTuple = [
    streamId: BytesLike,
    resumedAt: BigNumberish,
    newEndTime: BigNumberish
  ];
  export type OutputTuple = [
    streamId: string,
    resumedAt: bigint,
    newEndTime: bigint
  ];
  export interface OutputObject {
    streamId: string;
    resumedAt: bigint;
    newEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamWithdrawnEvent {
  export type InputTuple = [
    streamId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    streamId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    streamId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentStreamV2 extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentStreamV2;
  waitForDeployment(): Promise<this>;

  interface: PaymentStreamV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_STREAM_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_STREAM_DURATION: TypedContractMethod<[], [bigint], "view">;

  autoRenewalEnabled: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  availableBalance: TypedContractMethod<
    [streamId: BytesLike],
    [bigint],
    "view"
  >;

  cancelStream: TypedContractMethod<
    [streamId: BytesLike],
    [void],
    "nonpayable"
  >;

  createStream: TypedContractMethod<
    [
      recipient: AddressLike,
      amount: BigNumberish,
      duration: BigNumberish,
      serviceId: string,
      _autoRenew: boolean
    ],
    [string],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getAllStreamsForAddress: TypedContractMethod<
    [user: AddressLike],
    [string[]],
    "view"
  >;

  getRecipientStreams: TypedContractMethod<
    [recipient: AddressLike],
    [string[]],
    "view"
  >;

  getSenderStreams: TypedContractMethod<
    [sender: AddressLike],
    [string[]],
    "view"
  >;

  getStream: TypedContractMethod<
    [streamId: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        bigint,
        bigint
      ] & {
        sender: string;
        recipient: string;
        depositAmount: bigint;
        withdrawnAmount: bigint;
        startTime: bigint;
        endTime: bigint;
        ratePerSecond: bigint;
        status: bigint;
        serviceId: string;
        autoRenew: boolean;
        remainingTime: bigint;
        availableNow: bigint;
      }
    ],
    "view"
  >;

  getStreamsByStatus: TypedContractMethod<
    [user: AddressLike, _status: BigNumberish],
    [string[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pauseStream: TypedContractMethod<[streamId: BytesLike], [void], "nonpayable">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  recipientStreams: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resumeStream: TypedContractMethod<
    [streamId: BytesLike],
    [void],
    "nonpayable"
  >;

  senderStreams: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  setAutoRenewal: TypedContractMethod<
    [recipient: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setFeeRecipient: TypedContractMethod<
    [newFeeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  streamCount: TypedContractMethod<[], [bigint], "view">;

  streams: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        sender: string;
        recipient: string;
        depositAmount: bigint;
        withdrawnAmount: bigint;
        startTime: bigint;
        endTime: bigint;
        ratePerSecond: bigint;
        status: bigint;
        serviceId: string;
        pausedTime: bigint;
        totalPaused: bigint;
        autoRenew: boolean;
        renewalCount: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdt: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<[streamId: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_STREAM_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STREAM_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "autoRenewalEnabled"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "availableBalance"
  ): TypedContractMethod<[streamId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelStream"
  ): TypedContractMethod<[streamId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createStream"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      amount: BigNumberish,
      duration: BigNumberish,
      serviceId: string,
      _autoRenew: boolean
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllStreamsForAddress"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRecipientStreams"
  ): TypedContractMethod<[recipient: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSenderStreams"
  ): TypedContractMethod<[sender: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getStream"
  ): TypedContractMethod<
    [streamId: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        bigint,
        bigint
      ] & {
        sender: string;
        recipient: string;
        depositAmount: bigint;
        withdrawnAmount: bigint;
        startTime: bigint;
        endTime: bigint;
        ratePerSecond: bigint;
        status: bigint;
        serviceId: string;
        autoRenew: boolean;
        remainingTime: bigint;
        availableNow: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStreamsByStatus"
  ): TypedContractMethod<
    [user: AddressLike, _status: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pauseStream"
  ): TypedContractMethod<[streamId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recipientStreams"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resumeStream"
  ): TypedContractMethod<[streamId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "senderStreams"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAutoRenewal"
  ): TypedContractMethod<
    [recipient: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[newFeeRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "streamCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "streams"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        sender: string;
        recipient: string;
        depositAmount: bigint;
        withdrawnAmount: bigint;
        startTime: bigint;
        endTime: bigint;
        ratePerSecond: bigint;
        status: bigint;
        serviceId: string;
        pausedTime: bigint;
        totalPaused: bigint;
        autoRenew: boolean;
        renewalCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[streamId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "AutoRenewalToggled"
  ): TypedContractEvent<
    AutoRenewalToggledEvent.InputTuple,
    AutoRenewalToggledEvent.OutputTuple,
    AutoRenewalToggledEvent.OutputObject
  >;
  getEvent(
    key: "NotificationSent"
  ): TypedContractEvent<
    NotificationSentEvent.InputTuple,
    NotificationSentEvent.OutputTuple,
    NotificationSentEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "StreamCancelled"
  ): TypedContractEvent<
    StreamCancelledEvent.InputTuple,
    StreamCancelledEvent.OutputTuple,
    StreamCancelledEvent.OutputObject
  >;
  getEvent(
    key: "StreamCompleted"
  ): TypedContractEvent<
    StreamCompletedEvent.InputTuple,
    StreamCompletedEvent.OutputTuple,
    StreamCompletedEvent.OutputObject
  >;
  getEvent(
    key: "StreamCreated"
  ): TypedContractEvent<
    StreamCreatedEvent.InputTuple,
    StreamCreatedEvent.OutputTuple,
    StreamCreatedEvent.OutputObject
  >;
  getEvent(
    key: "StreamPaused"
  ): TypedContractEvent<
    StreamPausedEvent.InputTuple,
    StreamPausedEvent.OutputTuple,
    StreamPausedEvent.OutputObject
  >;
  getEvent(
    key: "StreamRenewed"
  ): TypedContractEvent<
    StreamRenewedEvent.InputTuple,
    StreamRenewedEvent.OutputTuple,
    StreamRenewedEvent.OutputObject
  >;
  getEvent(
    key: "StreamResumed"
  ): TypedContractEvent<
    StreamResumedEvent.InputTuple,
    StreamResumedEvent.OutputTuple,
    StreamResumedEvent.OutputObject
  >;
  getEvent(
    key: "StreamWithdrawn"
  ): TypedContractEvent<
    StreamWithdrawnEvent.InputTuple,
    StreamWithdrawnEvent.OutputTuple,
    StreamWithdrawnEvent.OutputObject
  >;

  filters: {
    "AutoRenewalToggled(address,address,bool)": TypedContractEvent<
      AutoRenewalToggledEvent.InputTuple,
      AutoRenewalToggledEvent.OutputTuple,
      AutoRenewalToggledEvent.OutputObject
    >;
    AutoRenewalToggled: TypedContractEvent<
      AutoRenewalToggledEvent.InputTuple,
      AutoRenewalToggledEvent.OutputTuple,
      AutoRenewalToggledEvent.OutputObject
    >;

    "NotificationSent(bytes32,address,string,string)": TypedContractEvent<
      NotificationSentEvent.InputTuple,
      NotificationSentEvent.OutputTuple,
      NotificationSentEvent.OutputObject
    >;
    NotificationSent: TypedContractEvent<
      NotificationSentEvent.InputTuple,
      NotificationSentEvent.OutputTuple,
      NotificationSentEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "StreamCancelled(bytes32,address,uint256)": TypedContractEvent<
      StreamCancelledEvent.InputTuple,
      StreamCancelledEvent.OutputTuple,
      StreamCancelledEvent.OutputObject
    >;
    StreamCancelled: TypedContractEvent<
      StreamCancelledEvent.InputTuple,
      StreamCancelledEvent.OutputTuple,
      StreamCancelledEvent.OutputObject
    >;

    "StreamCompleted(bytes32,bool)": TypedContractEvent<
      StreamCompletedEvent.InputTuple,
      StreamCompletedEvent.OutputTuple,
      StreamCompletedEvent.OutputObject
    >;
    StreamCompleted: TypedContractEvent<
      StreamCompletedEvent.InputTuple,
      StreamCompletedEvent.OutputTuple,
      StreamCompletedEvent.OutputObject
    >;

    "StreamCreated(bytes32,address,address,uint256,uint256,uint256,string,bool)": TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;
    StreamCreated: TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;

    "StreamPaused(bytes32,uint256,uint256)": TypedContractEvent<
      StreamPausedEvent.InputTuple,
      StreamPausedEvent.OutputTuple,
      StreamPausedEvent.OutputObject
    >;
    StreamPaused: TypedContractEvent<
      StreamPausedEvent.InputTuple,
      StreamPausedEvent.OutputTuple,
      StreamPausedEvent.OutputObject
    >;

    "StreamRenewed(bytes32,bytes32,uint256,uint256)": TypedContractEvent<
      StreamRenewedEvent.InputTuple,
      StreamRenewedEvent.OutputTuple,
      StreamRenewedEvent.OutputObject
    >;
    StreamRenewed: TypedContractEvent<
      StreamRenewedEvent.InputTuple,
      StreamRenewedEvent.OutputTuple,
      StreamRenewedEvent.OutputObject
    >;

    "StreamResumed(bytes32,uint256,uint256)": TypedContractEvent<
      StreamResumedEvent.InputTuple,
      StreamResumedEvent.OutputTuple,
      StreamResumedEvent.OutputObject
    >;
    StreamResumed: TypedContractEvent<
      StreamResumedEvent.InputTuple,
      StreamResumedEvent.OutputTuple,
      StreamResumedEvent.OutputObject
    >;

    "StreamWithdrawn(bytes32,address,uint256)": TypedContractEvent<
      StreamWithdrawnEvent.InputTuple,
      StreamWithdrawnEvent.OutputTuple,
      StreamWithdrawnEvent.OutputObject
    >;
    StreamWithdrawn: TypedContractEvent<
      StreamWithdrawnEvent.InputTuple,
      StreamWithdrawnEvent.OutputTuple,
      StreamWithdrawnEvent.OutputObject
    >;
  };
}
